### PR TITLE
Enter key to input new lines

### PR DESCRIPTION
**Pull request by beeender**

### CODE REVIEW

**Comment by higuoxing** [comment]
You're really a script ninja! Can we provide some simple syntax for user to configure? For example, I prefer using `<ctrl>+Enter` to inert a newline and using `Enter` to send the message.

**Comment by beeender** [comment]
What is the pattern for tempermonkey user to config? Manually edit the script?
We can have something on the top of the file like:

```
/* Config */
const config = {
  ctrl_enter_to_send: true,
};
```

Will this work?

BTW, how difficult to turn this into a firefox addon?

**Comment by higuoxing** [comment]
> What is the pattern for tempermonkey user to config? Manually edit the script? We can have something on the top of the file like:
> 
> ```
> /* Config */
> const config = {
>   ctrl_enter_to_send: true,
> };
> ```
> 
> Will this work?

Yeah. I think it will work.

> BTW, how difficult to turn this into a firefox addon?

You can install [the firefox version of tampermonkey addon](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) and install this script from https://greasyfork.org/en/scripts/483445-enhanced-google-chat.

**Comment by higuoxing** [comment]
@beeender, I pushed a new commit to your branch. The elements of HTML are obfuscated and their class names may get changed in the next release of Google Chat. Instead of locating elements with class names, locating them in a flexible way seems better.

**Comment by beeender** [comment]
> @beeender, I pushed a new commit to your branch. The elements of HTML are obfuscated and their class names may get changed in the next release of Google Chat. Instead of locating elements with class names, locating them in a flexible way seems better.

Sure, let's hope it will be more stable than the obfuscated tags :P

**Pull request merged**
